### ISSUE TITLE
Make photo on wrong pass

### ISSUE THREAD

**Issue by Corey-Maler** [IGRSoft/LockMeNow#1]
When someone trying to enter wrong pass some times, make a photo by web-cam

**Comment by ikorich** [comment]
will be available soon

**Comment by ikorich** [comment]
could you check it http://downloads.igrsoft.com/beta/LockMeNow_120_beat.zip

**Comment by Corey-Maler** [comment]
500 error on link :(

**Comment by ikorich** [comment]
Sorry, text mistake http://downloads.igrsoft.com/beta/LockMeNow_120_beta.zip

**Comment by Corey-Maler** [comment]
No, it doesn't work on my mac. May be I have conflict with app «knot to unlock», or I just can't found photos, but in ~/Pictures and ~/ and ~/Desktop clean.
- P.S. green indicator doesn't flash either.

And email with or without photo I don't receive.

Mac OS X 10.10.

**Comment by ikorich** [comment]
Do you apply patch for asl on a security tab?

**Comment by ikorich** [comment]
And do you lock mac via Lock Me Now or Knot to Unlock?

**Comment by Corey-Maler** [comment]
Sorry. I tried again. I turn off Knock, tried different settings, but no photo and no email :(

_I from Russia too, if interesting -- you can write me by mail: re_devil@live.ru for details. English is difficult for me :(_

**Comment by ikorich** [comment]
Ok

PS. I'm from Ukraine ;P

**Comment by ikorich** [comment]
@Corey-Maler ты получил письма?
