### ISSUE TITLE
Missing option in LockMeNow in V1.4.0

### ISSUE THREAD

**Issue by Torpidlittle** [IGRSoft/LockMeNow#14]
Hi,

I installed version 1.4.0 and the locking to "Login window" locking windows is missing ??!!
We can only "Lock the Screen".

Please bring this very handy option back !

Thanks,
Torpidlittle

**Comment by ikorich** [comment]
Hi @Torpidlittle 

Returned in v1.4.1 - https://github.com/IGRSoft/LockMeNow/releases/tag/v1.4.1

**Comment by Torpidlittle** [comment]
Thank you !

Torpidlittle
