### ISSUE TITLE
1.3.1 version crash

### ISSUE THREAD

**Issue by gaydba** [IGRSoft/LockMeNow#5]
hello
with 1.3.1 update lock me now crashes on me
silently

i found crash log in Library and pasted it http://pastebin.com/4KBiK9KW

downgraded version (1.3.0) works fine

**Comment by ikorich** [comment]
Hi @gaydba 

try to open via context menu (first time)
http://i.imgur.com/QsJQvGn.png

**Comment by gaydba** [comment]
be sure i tried

**Comment by ikorich** [comment]
All Certificates has beed updated.

Please remove app by http://freemacsoft.net/appcleaner/
and install latest version: https://downloads.igrsoft.com/lockmenow/LockMeNow_133.dmg.zip

**Comment by gaydba** [comment]
The requested URL /lockmenow/LockMeNow_133.dmg.zip was not found on this server.

**Comment by gaydba** [comment]
ok, it works without https

**Comment by gaydba** [comment]
this version runs just fine
thx
