### ISSUE TITLE
v1.3.3 not working

### ISSUE THREAD

**Issue by luis-manzano** [IGRSoft/LockMeNow#8]
Hi,

I have been receiving  v1.3.3 update available for a long time every time 1.3.2 starts but installing it automatically always fails (on "El Capitan" and "Sierra").

I manage to download 1.3.3 dmg from GITHUB and the link given in 1.3.1 crash issue closed and can put 1.3.3 container to Applications, but whenever I try to execute it from MacOS Sierra it states "It can not be opened. You should move it to trash".

I have already enabled opening unsigned apps through "sudo spctl --master-disable" in a terminal and I run it through CTRL+MENU way with same results.

If I execute: `spctl --asses --path /Applications/LockMeNow.app/`
I get: `/Applications/LockMeNow.app/: CSSMERR_TP_CERT_REVOKED`

If I try to open it from console, once I have removed com.apple.quarantine extended attribute, I get the following:

```
open LockMeNow.app/
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/LockMeNow.app.
```

I have also tried to cleanup afterwards v1.3.2 which was working properly trough "CleanApp" app as suggested and now I suffer same problem with all versions :-(

It seems developer certificate has been revoked so the app can not be executed anymore :-( Anyone can rebuild it signing it with a valid one?

**Any feedback on this issue?** 

BR and thanks for your contribution to this great app.

**Comment by ikorich** [comment]
Hi @genoso, 

I'll check it next week

**Comment by luis-manzano** [comment]
Hi @iKorich,

Thanks a lot! looking forward for your feedback next week ;-)

In the meanwhile I tried to compile the project with Xcode but I can not since I do not belong to development team and need certificates.

By the way, I could help with the project translating it into Spanish if you are interested into making it multilanguage.

BR,
/Luis

**Comment by luis-manzano** [comment]
Hi @iKorich,

Any update on this issue?

Thanks in advance,
/Luis

**Comment by ikorich** [comment]
Hi @genoso please, check new version http://downloads.igrsoft.com/lockmenow/LockMeNow_134.dmg.zip

**Comment by luis-manzano** [comment]
Hi @iKorich,

Here you are the feedback on the version you have provided executed on MacOS Sierra. I appreciate your steps!!!
- I only managed to start it for the first time allowing unsigned apps through "sudo spctl --master-disable" in a terminal. Even if I have external signed apps enabled and I run it through CTRL+MENU way, I get the window message stating to through the app to the trash.
- So far, it works ok, I have tried several system reboots and it starts automatically without issues. I have assigned a"shortcut keys" combination to lock computer and it works.
- I do not use any of the advanced features, such as "Security", "Bluetooth" nor "USB", so I can not give feedback on them.

In my case, problem seems solved ;-) Thanks a lot!

**Comment by ikorich** [comment]
@genoso ok, I'll check it on another macbook ;)

**Comment by luis-manzano** [comment]
Hi @iKorich,

In case Gatekeeper changes introduced in Sierra help with this issue, here you are a video for developers about those changes:

[https://developer.apple.com/videos/play/wwdc2016/706/?time=1339](url)

**Comment by ikorich** [comment]
Updated codesign in v1.4.0
