### ISSUE TITLE
App fails to start on macOS Sierra

### ISSUE THREAD

**Issue by r-haas** [IGRSoft/LockMeNow#9]
After upgrading to macOS Sierra, I can no longer start LockMeNow. The previous version that I had installed via the Mac App Store under Mac OS X El Capitan failed to start, informing me that I'd need to install a newer version via the App Store. No update was available in the App Store, so I downloaded the latest build from GitHub and got the attached error message.
![screen shot 2016-09-23 at 10 12 56 am](https://cloud.githubusercontent.com/assets/3084512/18794837/59a94352-8176-11e6-8082-98a5b0814e02.png)

**Comment by ikorich** [comment]
Hi @r-haas , 
I'll check it next week

**Comment by r-haas** [comment]
Excellent. Thank you!

**Comment by ikorich** [comment]
Hi @r-haas  please, check new version http://downloads.igrsoft.com/lockmenow/LockMeNow_134.dmg.zip

**Comment by Qteb** [comment]
@iKorich yea, 1.3.4 works on Sierra!
![image](https://cloud.githubusercontent.com/assets/877437/19152527/0f4a6d4e-8bdb-11e6-97a9-85c11b6b36f5.png)

**Comment by Qteb** [comment]
@iKorich Should I open an issue if i found a bug in your unreleased version?

**Comment by r-haas** [comment]
It works! Thank you, @iKorich!
